// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGQ.Web.Data;

#nullable disable

namespace SGQ.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909210928_AddAnexos")]
    partial class AddAnexos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SGQ.Web.Models.AcaoNaoConformidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataConclusao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Evidencia")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("NaoConformidadeId")
                        .HasColumnType("integer");

                    b.Property<bool>("Obrigatoria")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Prazo")
                        .HasColumnType("date");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NaoConformidadeId");

                    b.ToTable("AcoesNaoConformidade");
                });

            modelBuilder.Entity("SGQ.Web.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("EnviadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NaoConformidadeId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArmazenado")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int?>("RecallId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReclamacaoClienteId")
                        .HasColumnType("integer");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NaoConformidadeId");

                    b.HasIndex("RecallId");

                    b.HasIndex("ReclamacaoClienteId");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("SGQ.Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SGQ.Web.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SGQ.Web.Models.HistoricoAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Alteracoes")
                        .HasColumnType("text");

                    b.Property<string>("ChaveRegistro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("OcorridaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("HistoricosAuditoria");
                });

            modelBuilder.Entity("SGQ.Web.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("SGQ.Web.Models.NaoConformidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<bool>("AprovadaGq")
                        .HasColumnType("boolean");

                    b.Property<bool>("AprovadaRt")
                        .HasColumnType("boolean");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CausaProvavel")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("CausaRaiz")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Classificacao")
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Contencao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool?>("Eficaz")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EncerradaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Investigacao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("MetodoAnalise")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReclamacaoClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("SequenciaAnual")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAbertura")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UsuarioEncerramento")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ReclamacaoClienteId")
                        .IsUnique();

                    b.HasIndex("Ano", "SequenciaAnual")
                        .IsUnique();

                    b.ToTable("NaoConformidades");
                });

            modelBuilder.Entity("SGQ.Web.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SGQ.Web.Models.Recall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<bool>("AprovadaGq")
                        .HasColumnType("boolean");

                    b.Property<bool>("AprovadaRt")
                        .HasColumnType("boolean");

                    b.Property<string>("AutoridadeSanitaria")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("BloqueioRegistrado")
                        .HasColumnType("boolean");

                    b.Property<string>("ClientesEnvolvidos")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ComunicacaoClientes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ComunicadaAutoridadeEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataFabricacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataValidade")
                        .HasColumnType("date");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destinacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("EncerradaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenciaDestinacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("JustificativaDecisao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<int?>("NaoConformidadeId")
                        .HasColumnType("integer");

                    b.Property<string>("NaturezaOcorrencia")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<string>("ProtocoloAutoridade")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("QuantidadeDistribuida")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantidadeEstoque")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantidadeProduzida")
                        .HasColumnType("numeric");

                    b.Property<int?>("ReclamacaoClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("RiscoPotencial")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("SequenciaAnual")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAbertura")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UsuarioEncerramento")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("LoteId");

                    b.HasIndex("NaoConformidadeId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ReclamacaoClienteId");

                    b.HasIndex("Ano", "SequenciaAnual")
                        .IsUnique();

                    b.ToTable("Recalls");
                });

            modelBuilder.Entity("SGQ.Web.Models.ReclamacaoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("CanalRecebimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Classificacao")
                        .HasColumnType("text");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContatoCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFabricacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataRecebimento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataRespostaCliente")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataValidade")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("EncerradaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Investigacao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("LocalAquisicao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ProdutoDisponivel")
                        .HasColumnType("boolean");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("QuantidadeDisponivel")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("QuantidadeEnvolvida")
                        .HasColumnType("numeric");

                    b.Property<string>("RespostaCliente")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Resultado")
                        .HasColumnType("text");

                    b.Property<int>("SequenciaAnual")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TratamentoAplicado")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("UsuarioAbertura")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UsuarioEncerramento")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UsuarioValidacao")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ValidadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VolumeDisponivel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ProdutoId");

                    b.HasIndex("Ano", "SequenciaAnual")
                        .IsUnique();

                    b.ToTable("ReclamacoesClientes");
                });

            modelBuilder.Entity("SGQ.Web.Models.ReclamacaoClienteLote", b =>
                {
                    b.Property<int>("ReclamacaoClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.HasKey("ReclamacaoClienteId", "LoteId");

                    b.HasIndex("LoteId");

                    b.ToTable("ReclamacaoClienteLote");
                });

            modelBuilder.Entity("SGQ.Web.Models.RetornoRecall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvaliacaoGq")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Avarias")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CondicaoEmbalagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CondicaoLacre")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("DataRetorno")
                        .HasColumnType("date");

                    b.Property<string>("DocumentoTransporte")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<int>("RecallId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecallId");

                    b.ToTable("RetornosRecall");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SGQ.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SGQ.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGQ.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SGQ.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGQ.Web.Models.AcaoNaoConformidade", b =>
                {
                    b.HasOne("SGQ.Web.Models.NaoConformidade", "NaoConformidade")
                        .WithMany("Acoes")
                        .HasForeignKey("NaoConformidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NaoConformidade");
                });

            modelBuilder.Entity("SGQ.Web.Models.Anexo", b =>
                {
                    b.HasOne("SGQ.Web.Models.NaoConformidade", null)
                        .WithMany()
                        .HasForeignKey("NaoConformidadeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SGQ.Web.Models.Recall", null)
                        .WithMany()
                        .HasForeignKey("RecallId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SGQ.Web.Models.ReclamacaoCliente", null)
                        .WithMany()
                        .HasForeignKey("ReclamacaoClienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SGQ.Web.Models.Lote", b =>
                {
                    b.HasOne("SGQ.Web.Models.Produto", "Produto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SGQ.Web.Models.NaoConformidade", b =>
                {
                    b.HasOne("SGQ.Web.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGQ.Web.Models.ReclamacaoCliente", "ReclamacaoCliente")
                        .WithOne("NaoConformidade")
                        .HasForeignKey("SGQ.Web.Models.NaoConformidade", "ReclamacaoClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Produto");

                    b.Navigation("ReclamacaoCliente");
                });

            modelBuilder.Entity("SGQ.Web.Models.Recall", b =>
                {
                    b.HasOne("SGQ.Web.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGQ.Web.Models.NaoConformidade", "NaoConformidade")
                        .WithMany()
                        .HasForeignKey("NaoConformidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGQ.Web.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGQ.Web.Models.ReclamacaoCliente", "ReclamacaoCliente")
                        .WithMany()
                        .HasForeignKey("ReclamacaoClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lote");

                    b.Navigation("NaoConformidade");

                    b.Navigation("Produto");

                    b.Navigation("ReclamacaoCliente");
                });

            modelBuilder.Entity("SGQ.Web.Models.ReclamacaoCliente", b =>
                {
                    b.HasOne("SGQ.Web.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGQ.Web.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SGQ.Web.Models.ReclamacaoClienteLote", b =>
                {
                    b.HasOne("SGQ.Web.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGQ.Web.Models.ReclamacaoCliente", "ReclamacaoCliente")
                        .WithMany("Lotes")
                        .HasForeignKey("ReclamacaoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("ReclamacaoCliente");
                });

            modelBuilder.Entity("SGQ.Web.Models.RetornoRecall", b =>
                {
                    b.HasOne("SGQ.Web.Models.Recall", "Recall")
                        .WithMany("Retornos")
                        .HasForeignKey("RecallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recall");
                });

            modelBuilder.Entity("SGQ.Web.Models.NaoConformidade", b =>
                {
                    b.Navigation("Acoes");
                });

            modelBuilder.Entity("SGQ.Web.Models.Produto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("SGQ.Web.Models.Recall", b =>
                {
                    b.Navigation("Retornos");
                });

            modelBuilder.Entity("SGQ.Web.Models.ReclamacaoCliente", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("NaoConformidade");
                });
#pragma warning restore 612, 618
        }
    }
}
